name: refri_mobile
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.1.1
  intl: ^0.17.0
  flutter_svg: ^1.1.4
  dio: ^4.0.6
  convex_bottom_bar: ^3.0.0
  flutter_native_splash: ^2.2.11
  google_sign_in: ^5.4.2
  flutter_local_notifications: ^12.0.2
  firebase_core: ^2.1.0
  firebase_analytics: ^10.0.2
  firebase_messaging: ^14.0.2
  firebase_crashlytics: ^3.0.2
  firebase_app_check: ^0.1.1+1
  firebase_auth: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - asset/img/
    - asset/svg/

  fonts:
    - family: NotoSans
      fonts:
        - asset: asset/font/NotoSansKR-Black.otf
          weight: 900
        - asset: asset/font/NotoSansKR-Bold.otf
          weight: 700
        - asset: asset/font/NotoSansKR-Medium.otf
          weight: 500
        - asset: asset/font/NotoSansKR-Regular.otf
          weight: 400
        - asset: asset/font/NotoSansKR-Light.otf
          weight: 300
        - asset: asset/font/NotoSansKR-Thin.otf
          weight: 100

  uses-material-design: true

flutter_native_splash:
  background_image: "asset/img/splash.png"
  android_12:
